version: "3"
services:
  db:
    image: mysql:5.7
    networks:
      - web-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=dostavim
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
#    healthcheck:
#      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
#      timeout: 20s
#      retries: 2
#    volumes:
#      - ./scripts/CREATE.sql:/docker-entrypoint-initdb.d/initdb.sql

  web-app:
    build: ./DostavimVse
    ports:
      - 8080:8080
    networks:
      - web-db
    depends_on:
      - db

networks:
  web-db: